### ISSUE TITLE
Field does not work as expected with translationMethod is none on a multisite installation

### ISSUE THREAD

**Issue by andersaloof** [vangenplotz/Craft-Imageshop#18]
We've added this field to an entry (Article) on a multisite (norwegian and english). The translationMethod is set to `none`.

When we access an entry in norwegian and select an image, the field is empty when switching to the english version of the entry. If we select an image on the english version and switch back to the norwegian version, the norwegian verison is empty and has lost it's selected image.

The expected result is that the selected image is identical across all languages when the translationMethods is none.

PHP version 7.4.14
Craft edition & version Craft Pro 3.5.17.1

**Comment by andersaloof** [comment]
I've submitted a PR for this #23

**Comment by urielbeaupre** [comment]
PR has now been merged
